/*Validate Authenticate User Model */
export const VALIDATE_AUTHUSER_SUCCESS = "VALIDATE_AUTHUSER_SUCCESS";
export const VALIDATE_AUTHUSER_FAILURE = "VALIDATE_AUTHUSER_FAILURE";
export const VALIDATE_AUTHUSER_MODEL_ERROR  = "VALIDATE_AUTHUSER_MODEL_ERROR";
export const LOGOUT_AUTHUSER_SUCCESS  = "LOGOUT_AUTHUSER_SUCCESS";
export const COOKIE_VALIDATION_FAILED  = "COOKIE_VALIDATION_FAILED";
/*Insert Update,Select User Details User Model */
export const INSERT_USER_SUCCESS = "INSERT_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const USER_MODEL_ERRORS = "USER_MODEL_ERRORS";
export const SCH_USER_DETAILS_SUCCESS = "SCH_USER_DETAILS_SUCCESS";
export const SCH_USER_DETAILS_ERROR = "SCH_USER_DETAILS_ERROR";



/*Reference Data */
export const GET_REF_CMB_YEAR_SUCCESS = "GET_REF_CMB_YEAR_SUCCESS";
export const GET_REF_CMB_YEAR_ERROR = "GET_REF_CMB_YEAR_ERROR";
export const RESET_REDUX_SUCCESS = "RESET_REDUX_SUCCESS";

//Registration Constants
export const GET_REF_COUNTRY_SUCCESS = "GET_REF_COUNTRY_SUCCESS";
export const GET_REF_COUNTRY_ERROR = "GET_REF_COUNTRY_ERROR";
export const GET_REF_QUESTION_CHOICE_SUCCESS = "GET_REF_QUESTION_CHOICE_SUCCESS";
export const GET_REF_QUESTION_CHOICE_ERROR = "GET_REF_QUESTION_CHOICE_ERROR";
export const GET_REF_QUESTION_SUCCESS = "GET_REF_QUESTION_SUCCESS";
export const GET_REF_QUESTION_ERROR = "GET_REF_QUESTION_ERROR";
export const GET_REF_REGUSER_INITIAL_MODEL_SUCCESS = "GET_REF_REGUSER_INITIAL_MODEL_SUCCESS";
export const GET_REF_REGUSER_INITIAL_MODEL_ERROR = "GET_REF_REGUSER_INITIAL_MODEL_ERROR";
